#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "aarch64-linux-android-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DTERMIO -O3 -Wall -pie -fPIE"
  #define PLATFORM "linux-armv4"
  #define DATE "Fri Sep  4 10:45:09 CST 2020"
#endif
